image: mcr.microsoft.com/dotnet/sdk:5.0-alpine

variables:
  BUILD_FOLDER: Finance.PciDss.Bridge.RealDeposits.Server
  DOCKER_IMAGE_TAG: monfex/pci-dss-bridge-realdeposits-server
  TEST_FOLDER: Finance.PciDss.Bridge.RealDeposits.Server.Tests

include:
  - project: 'MONFEX-DEVOPS/infrastructure_builder'
    ref: master
    file: '/.gitlab-ci.yml'